/* The following code was generated by JFlex 1.7.0 */

package grammar;

import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;

import static grammar.Token.*;

import java.io.Reader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/Users/smg247/Projects/COFC/CSIS618/tinyJavaCompiler/src/main/java/grammar/grammar.jflex</tt>
 */
public class TinyJavaLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\1\1\12\1\12\1\2\22\0\1\15\1\47\1\14"+
    "\5\0\1\55\1\54\1\17\1\43\1\45\1\11\1\46\1\16\1\6"+
    "\11\5\1\0\1\44\1\50\1\42\1\51\2\0\4\3\1\10\1\13"+
    "\24\3\1\53\1\0\1\52\1\0\1\3\1\0\1\36\1\34\1\35"+
    "\1\41\1\22\1\21\1\3\1\26\1\20\2\3\1\23\1\3\1\32"+
    "\1\40\1\33\1\3\1\27\1\24\1\30\1\31\1\37\1\25\3\3"+
    "\1\56\1\7\1\57\7\0\1\12\32\0\1\15\11\0\1\4\12\0"+
    "\1\4\4\0\1\4\5\0\27\4\1\0\37\4\1\0\u01ca\4\4\0"+
    "\14\4\16\0\5\4\7\0\1\4\1\0\1\4\21\0\165\4\1\0"+
    "\2\4\2\0\4\4\1\0\1\4\6\0\1\4\1\0\3\4\1\0"+
    "\1\4\1\0\24\4\1\0\123\4\1\0\213\4\1\0\255\4\1\0"+
    "\46\4\2\0\1\4\7\0\47\4\11\0\55\4\1\0\1\4\1\0"+
    "\2\4\1\0\2\4\1\0\1\4\10\0\33\4\5\0\3\4\35\0"+
    "\13\4\5\0\100\4\12\6\4\0\146\4\1\0\10\4\2\0\12\4"+
    "\1\0\6\4\12\6\3\4\2\0\1\4\20\0\73\4\2\0\145\4"+
    "\16\0\12\6\54\4\4\0\1\4\5\0\56\4\22\0\34\4\104\0"+
    "\25\4\1\0\10\4\26\0\16\4\1\0\201\4\2\0\12\6\1\0"+
    "\23\4\1\0\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0"+
    "\1\4\3\0\4\4\2\0\11\4\2\0\2\4\2\0\4\4\10\0"+
    "\1\4\4\0\2\4\1\0\5\4\2\0\12\6\2\4\17\0\3\4"+
    "\1\0\6\4\4\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4"+
    "\1\0\2\4\1\0\2\4\2\0\1\4\1\0\5\4\4\0\2\4"+
    "\2\0\3\4\3\0\1\4\7\0\4\4\1\0\1\4\7\0\12\6"+
    "\6\4\13\0\3\4\1\0\11\4\1\0\3\4\1\0\26\4\1\0"+
    "\7\4\1\0\2\4\1\0\5\4\2\0\12\4\1\0\3\4\1\0"+
    "\3\4\2\0\1\4\17\0\4\4\2\0\12\6\11\0\1\4\7\0"+
    "\3\4\1\0\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0"+
    "\2\4\1\0\5\4\2\0\11\4\2\0\2\4\2\0\3\4\10\0"+
    "\2\4\4\0\2\4\1\0\5\4\2\0\12\6\1\0\1\4\20\0"+
    "\2\4\1\0\6\4\3\0\3\4\1\0\4\4\3\0\2\4\1\0"+
    "\1\4\1\0\2\4\3\0\2\4\3\0\3\4\3\0\14\4\4\0"+
    "\5\4\3\0\3\4\1\0\4\4\2\0\1\4\6\0\1\4\16\0"+
    "\12\6\20\0\4\4\1\0\10\4\1\0\3\4\1\0\27\4\1\0"+
    "\20\4\3\0\10\4\1\0\3\4\1\0\4\4\7\0\2\4\1\0"+
    "\3\4\5\0\4\4\2\0\12\6\20\0\4\4\1\0\10\4\1\0"+
    "\3\4\1\0\27\4\1\0\12\4\1\0\5\4\2\0\11\4\1\0"+
    "\3\4\1\0\4\4\7\0\2\4\7\0\1\4\1\0\4\4\2\0"+
    "\12\6\1\0\2\4\16\0\3\4\1\0\10\4\1\0\3\4\1\0"+
    "\51\4\2\0\10\4\1\0\3\4\1\0\5\4\5\0\4\4\7\0"+
    "\5\4\2\0\12\6\12\0\6\4\2\0\2\4\1\0\22\4\3\0"+
    "\30\4\1\0\11\4\1\0\1\4\2\0\7\4\3\0\1\4\4\0"+
    "\6\4\1\0\1\4\1\0\10\4\6\0\12\6\2\0\2\4\15\0"+
    "\72\4\5\0\17\4\1\0\12\6\47\0\2\4\1\0\1\4\2\0"+
    "\2\4\1\0\1\4\2\0\1\4\6\0\4\4\1\0\7\4\1\0"+
    "\3\4\1\0\1\4\1\0\1\4\2\0\2\4\1\0\15\4\1\0"+
    "\3\4\2\0\5\4\1\0\1\4\1\0\6\4\2\0\12\6\2\0"+
    "\4\4\40\0\1\4\27\0\2\4\6\0\12\6\13\0\1\4\1\0"+
    "\1\4\1\0\1\4\4\0\12\4\1\0\44\4\4\0\24\4\1\0"+
    "\22\4\1\0\44\4\11\0\1\4\71\0\100\4\12\6\6\0\100\4"+
    "\12\6\4\4\2\0\46\4\1\0\1\4\5\0\1\4\2\0\53\4"+
    "\1\0\u014d\4\1\0\4\4\2\0\7\4\1\0\1\4\1\0\4\4"+
    "\2\0\51\4\1\0\4\4\2\0\41\4\1\0\4\4\2\0\7\4"+
    "\1\0\1\4\1\0\4\4\2\0\17\4\1\0\71\4\1\0\4\4"+
    "\2\0\103\4\2\0\3\4\40\0\20\4\20\0\126\4\2\0\6\4"+
    "\3\0\u026c\4\2\0\21\4\1\15\32\4\5\0\113\4\3\0\13\4"+
    "\7\0\15\4\1\0\7\4\13\0\25\4\13\0\24\4\14\0\15\4"+
    "\1\0\3\4\1\0\2\4\14\0\124\4\3\0\1\4\4\0\2\4"+
    "\2\0\12\6\41\0\3\4\2\0\12\6\6\0\130\4\10\0\53\4"+
    "\5\0\106\4\12\0\37\4\1\0\14\4\4\0\14\4\12\0\12\6"+
    "\36\4\2\0\5\4\13\0\54\4\4\0\32\4\6\0\12\6\46\0"+
    "\34\4\4\0\77\4\1\0\35\4\2\0\1\4\12\6\6\0\12\6"+
    "\15\0\1\4\10\0\17\4\101\0\114\4\4\0\12\6\21\0\11\4"+
    "\14\0\60\4\12\6\72\4\14\0\70\4\10\0\12\6\3\0\3\4"+
    "\12\6\44\4\2\0\11\4\107\0\3\4\1\0\43\4\1\0\2\4"+
    "\6\0\366\4\5\0\u011b\4\2\0\6\4\2\0\46\4\2\0\6\4"+
    "\2\0\10\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0\37\4"+
    "\2\0\65\4\1\0\7\4\1\0\1\4\3\0\3\4\1\0\7\4"+
    "\3\0\4\4\2\0\6\4\4\0\15\4\5\0\3\4\1\0\7\4"+
    "\3\0\13\15\35\0\1\12\1\12\5\0\1\15\17\0\2\4\23\0"+
    "\1\4\12\0\1\15\21\0\1\4\15\0\1\4\20\0\15\4\63\0"+
    "\41\4\21\0\1\4\4\0\1\4\2\0\12\4\1\0\1\4\3\0"+
    "\5\4\6\0\1\4\1\0\1\4\1\0\1\4\1\0\4\4\1\0"+
    "\13\4\2\0\4\4\5\0\5\4\4\0\1\4\21\0\51\4\u032d\0"+
    "\64\4\u0716\0\57\4\1\0\57\4\1\0\205\4\6\0\11\4\14\0"+
    "\46\4\1\0\1\4\5\0\1\4\2\0\70\4\7\0\1\4\17\0"+
    "\30\4\11\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0\40\4\57\0"+
    "\1\4\u01d0\0\1\15\4\0\3\4\31\0\17\4\1\0\5\4\2\0"+
    "\5\4\4\0\126\4\2\0\2\4\2\0\3\4\1\0\132\4\1\0"+
    "\4\4\5\0\51\4\3\0\136\4\21\0\33\4\65\0\20\4\u0200\0"+
    "\u19b6\4\112\0\u51d6\4\52\0\u048d\4\103\0\56\4\2\0\u010d\4\3\0"+
    "\20\4\12\6\2\4\24\0\63\4\1\0\12\4\1\0\163\4\45\0"+
    "\11\4\2\0\147\4\2\0\44\4\1\0\10\4\77\0\61\4\30\0"+
    "\64\4\14\0\106\4\12\0\12\6\6\0\30\4\3\0\1\4\1\0"+
    "\1\4\2\0\12\6\44\4\2\0\44\4\14\0\35\4\3\0\101\4"+
    "\16\0\1\4\12\6\6\0\20\4\12\6\5\4\1\0\67\4\11\0"+
    "\16\4\2\0\12\6\6\0\27\4\3\0\111\4\30\0\3\4\2\0"+
    "\20\4\2\0\5\4\12\0\6\4\2\0\6\4\2\0\6\4\11\0"+
    "\7\4\1\0\7\4\1\0\53\4\1\0\12\4\12\0\173\4\1\0"+
    "\2\4\2\0\12\6\6\0\u2ba4\4\14\0\27\4\4\0\61\4\u2104\0"+
    "\u016e\4\2\0\152\4\46\0\7\4\14\0\5\4\5\0\14\4\1\0"+
    "\15\4\1\0\5\4\1\0\1\4\1\0\2\4\1\0\2\4\1\0"+
    "\154\4\41\0\u016b\4\22\0\100\4\2\0\66\4\50\0\14\4\4\0"+
    "\20\4\20\0\20\4\3\0\2\4\30\0\3\4\40\0\5\4\1\0"+
    "\207\4\23\0\12\6\7\0\32\4\4\0\1\4\1\0\32\4\13\0"+
    "\131\4\3\0\6\4\2\0\6\4\2\0\6\4\2\0\3\4\43\0"+
    "\14\4\1\0\32\4\1\0\23\4\1\0\2\4\1\0\17\4\2\0"+
    "\16\4\42\0\173\4\105\0\65\4\210\0\1\4\202\0\35\4\3\0"+
    "\61\4\17\0\1\4\37\0\40\4\20\0\33\4\5\0\53\4\5\0"+
    "\36\4\2\0\44\4\4\0\10\4\1\0\5\4\52\0\236\4\2\0"+
    "\12\6\6\0\44\4\4\0\44\4\4\0\50\4\10\0\64\4\234\0"+
    "\u0137\4\11\0\26\4\12\0\10\4\230\0\6\4\2\0\1\4\1\0"+
    "\54\4\1\0\2\4\3\0\1\4\2\0\27\4\12\0\27\4\11\0"+
    "\37\4\101\0\23\4\1\0\2\4\12\0\26\4\12\0\32\4\106\0"+
    "\70\4\6\0\2\4\100\0\4\4\1\0\2\4\5\0\10\4\1\0"+
    "\3\4\1\0\33\4\4\0\3\4\4\0\1\4\40\0\35\4\3\0"+
    "\35\4\43\0\10\4\1\0\36\4\31\0\66\4\12\0\26\4\12\0"+
    "\23\4\15\0\22\4\156\0\111\4\67\0\63\4\15\0\63\4\u030d\0"+
    "\107\4\37\0\12\6\17\0\74\4\25\0\31\4\7\0\12\6\6\0"+
    "\65\4\1\0\12\6\20\0\44\4\2\0\1\4\11\0\105\4\5\0"+
    "\3\4\3\0\12\6\1\4\1\0\1\4\43\0\22\4\1\0\45\4"+
    "\6\0\1\4\101\0\7\4\1\0\1\4\1\0\4\4\1\0\17\4"+
    "\1\0\12\4\7\0\73\4\5\0\12\6\6\0\4\4\1\0\10\4"+
    "\2\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4\1\0\5\4"+
    "\2\0\11\4\2\0\2\4\2\0\3\4\2\0\1\4\6\0\1\4"+
    "\5\0\7\4\2\0\7\4\3\0\5\4\213\0\113\4\5\0\12\6"+
    "\46\0\106\4\1\0\1\4\10\0\12\6\246\0\66\4\2\0\11\4"+
    "\27\0\6\4\42\0\101\4\3\0\1\4\13\0\12\6\46\0\70\4"+
    "\10\0\12\6\66\0\32\4\3\0\17\4\4\0\12\6\u0166\0\100\4"+
    "\12\6\25\0\1\4\u01c0\0\71\4\u0107\0\11\4\1\0\55\4\1\0"+
    "\11\4\17\0\12\6\30\0\36\4\2\0\26\4\1\0\16\4\u0349\0"+
    "\u039a\4\146\0\157\4\21\0\304\4\u0abc\0\u042f\4\u0fd1\0\u0247\4\u21b9\0"+
    "\u0239\4\7\0\37\4\1\0\12\6\146\0\36\4\2\0\5\4\13\0"+
    "\67\4\11\0\4\4\14\0\12\6\11\0\25\4\5\0\23\4\u0370\0"+
    "\105\4\13\0\57\4\20\0\21\4\100\0\1\4\37\0\u17ed\4\23\0"+
    "\u02f3\4\u250d\0\2\4\u0bfe\0\153\4\5\0\15\4\3\0\11\4\7\0"+
    "\12\4\3\0\2\4\u14c6\0\5\4\3\0\6\4\10\0\10\4\2\0"+
    "\7\4\36\0\4\4\224\0\3\4\u01bb\0\125\4\1\0\107\4\1\0"+
    "\2\4\2\0\1\4\2\0\2\4\2\0\4\4\1\0\14\4\1\0"+
    "\1\4\1\0\7\4\1\0\101\4\1\0\4\4\2\0\10\4\1\0"+
    "\7\4\1\0\34\4\1\0\4\4\1\0\5\4\1\0\1\4\3\0"+
    "\7\4\1\0\u0154\4\2\0\31\4\1\0\31\4\1\0\37\4\1\0"+
    "\31\4\1\0\37\4\1\0\31\4\1\0\37\4\1\0\31\4\1\0"+
    "\37\4\1\0\31\4\1\0\10\4\2\0\62\6\u0200\0\67\4\4\0"+
    "\62\4\10\0\1\4\16\0\1\4\26\0\5\4\1\0\17\4\u0550\0"+
    "\7\4\1\0\21\4\2\0\7\4\1\0\2\4\1\0\5\4\u07d5\0"+
    "\305\4\13\0\7\4\51\0\113\4\5\0\12\6\u04a6\0\4\4\1\0"+
    "\33\4\1\0\2\4\1\0\1\4\2\0\1\4\1\0\12\4\1\0"+
    "\4\4\1\0\1\4\1\0\1\4\6\0\1\4\4\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\0\3\4\1\0\2\4\1\0\1\4\2\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0"+
    "\2\4\1\0\1\4\2\0\4\4\1\0\7\4\1\0\4\4\1\0"+
    "\4\4\1\0\1\4\1\0\12\4\1\0\21\4\5\0\3\4\1\0"+
    "\5\4\1\0\21\4\u0274\0\32\4\6\0\32\4\6\0\32\4\u0e76\0"+
    "\ua6d7\4\51\0\u1035\4\13\0\336\4\2\0\u1682\4\u295e\0\u021e\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\4\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\11\3\1\10\1\11\1\12\1\13\1\14\1\1"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\0\1\4\2\0\1\25\1\26\1\0\1\27\11\3"+
    "\1\30\1\31\1\32\1\33\1\34\1\4\1\34\2\26"+
    "\2\0\1\35\10\3\1\34\1\0\2\34\1\0\1\34"+
    "\1\0\1\36\5\3\1\37\1\3\3\34\1\3\1\40"+
    "\2\3\1\41\1\3\1\42\1\43\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\140\0\220\0\300\0\140\0\360"+
    "\0\u0120\0\140\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u02d0\0\u0300\0\140\0\140\0\140\0\140"+
    "\0\u0330\0\u0360\0\u0390\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\u03c0\0\u03f0\0\u0420\0\360\0\360\0\u0450\0\u0480"+
    "\0\220\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0"+
    "\0\u0600\0\u0630\0\140\0\140\0\140\0\140\0\u0660\0\u0690"+
    "\0\u06c0\0\140\0\u06f0\0\u0720\0\u0750\0\220\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930"+
    "\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\220\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\u0b10\0\220\0\u0b40\0\u0b70\0\u0930\0\140"+
    "\0\u0ba0\0\220\0\u0bd0\0\u0c00\0\220\0\u0c30\0\220\0\220"+
    "\0\220\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\3\2\6\1\3\1\5\1\7"+
    "\1\4\1\5\1\10\1\4\1\11\1\12\1\13\1\5"+
    "\1\14\1\5\1\15\1\16\1\5\1\17\3\5\1\20"+
    "\1\5\1\21\1\5\1\22\1\5\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\60\3\63\0\4\5\1\0"+
    "\1\5\2\0\1\5\4\0\22\5\16\0\1\42\2\0"+
    "\2\42\1\43\1\44\3\42\1\0\45\42\1\45\2\0"+
    "\7\45\1\0\1\45\1\46\43\45\16\0\1\47\1\50"+
    "\43\0\4\5\1\0\1\5\2\0\1\5\4\0\1\5"+
    "\1\51\10\5\1\52\7\5\21\0\4\5\1\0\1\5"+
    "\2\0\1\5\4\0\3\5\1\53\16\5\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\10\5\1\54\11\5"+
    "\21\0\4\5\1\0\1\5\2\0\1\5\4\0\6\5"+
    "\1\55\13\5\21\0\4\5\1\0\1\5\2\0\1\5"+
    "\4\0\2\5\1\56\17\5\21\0\4\5\1\0\1\5"+
    "\2\0\1\5\4\0\11\5\1\57\10\5\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\3\5\1\60\16\5"+
    "\21\0\4\5\1\0\1\5\2\0\1\5\4\0\20\5"+
    "\1\61\1\5\21\0\4\5\1\0\1\5\2\0\1\5"+
    "\4\0\20\5\1\62\1\5\60\0\1\63\57\0\1\64"+
    "\57\0\1\65\57\0\1\66\22\0\2\67\51\0\1\42"+
    "\2\0\2\42\1\70\1\71\3\42\1\0\46\42\2\0"+
    "\2\42\2\71\3\42\1\0\45\42\1\47\1\72\1\73"+
    "\55\47\17\74\1\75\40\74\3\0\4\5\1\0\1\5"+
    "\2\0\1\5\4\0\10\5\1\76\11\5\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\4\5\1\77\15\5"+
    "\21\0\4\5\1\0\1\5\2\0\1\5\4\0\16\5"+
    "\1\100\3\5\21\0\4\5\1\0\1\5\2\0\1\5"+
    "\4\0\1\101\21\5\21\0\4\5\1\0\1\5\2\0"+
    "\1\5\4\0\10\5\1\102\11\5\21\0\4\5\1\0"+
    "\1\5\2\0\1\5\4\0\14\5\1\103\5\5\21\0"+
    "\4\5\1\0\1\5\2\0\1\5\4\0\16\5\1\104"+
    "\3\5\21\0\4\5\1\0\1\5\2\0\1\5\4\0"+
    "\1\105\21\5\21\0\4\5\1\0\1\5\2\0\1\5"+
    "\4\0\11\5\1\106\10\5\23\0\2\67\1\107\1\110"+
    "\2\0\1\111\5\0\1\111\1\110\35\0\1\42\2\0"+
    "\2\42\1\70\1\71\1\112\1\113\1\42\1\0\1\114"+
    "\5\42\1\114\1\113\36\42\2\0\2\42\2\71\1\112"+
    "\1\113\1\42\1\0\1\114\5\42\1\114\1\113\35\42"+
    "\1\0\1\72\56\0\17\74\1\115\40\74\16\0\1\72"+
    "\1\75\43\0\4\5\1\0\1\5\2\0\1\5\4\0"+
    "\2\5\1\116\17\5\21\0\4\5\1\0\1\5\2\0"+
    "\1\5\4\0\10\5\1\117\11\5\21\0\4\5\1\0"+
    "\1\5\2\0\1\5\4\0\3\5\1\120\16\5\21\0"+
    "\4\5\1\0\1\5\2\0\1\5\4\0\11\5\1\121"+
    "\10\5\21\0\4\5\1\0\1\5\2\0\1\5\4\0"+
    "\3\5\1\122\16\5\21\0\4\5\1\0\1\5\2\0"+
    "\1\5\4\0\4\5\1\123\15\5\21\0\4\5\1\0"+
    "\1\5\2\0\1\5\4\0\21\5\1\124\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\14\5\1\125\5\5"+
    "\23\0\2\126\1\127\1\110\1\130\10\0\1\110\20\0"+
    "\1\130\21\0\3\130\1\0\1\130\31\0\1\130\21\0"+
    "\2\126\2\110\11\0\1\110\42\0\2\67\1\127\1\110"+
    "\1\130\10\0\1\110\20\0\1\130\21\0\2\67\1\130"+
    "\1\0\1\130\31\0\1\130\21\0\2\67\2\110\11\0"+
    "\1\110\35\0\16\74\1\72\1\115\40\74\3\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\1\131\21\5\21\0"+
    "\4\5\1\0\1\5\2\0\1\5\4\0\2\5\1\132"+
    "\17\5\21\0\4\5\1\0\1\5\2\0\1\5\4\0"+
    "\7\5\1\133\12\5\21\0\4\5\1\0\1\5\2\0"+
    "\1\5\4\0\1\134\21\5\21\0\4\5\1\0\1\5"+
    "\2\0\1\5\4\0\4\5\1\135\15\5\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\3\5\1\136\16\5"+
    "\23\0\2\126\54\0\4\5\1\0\1\5\2\0\1\5"+
    "\4\0\15\5\1\137\4\5\21\0\4\5\1\0\1\5"+
    "\2\0\1\5\4\0\12\5\1\140\7\5\21\0\4\5"+
    "\1\0\1\5\2\0\1\5\4\0\15\5\1\141\4\5"+
    "\21\0\4\5\1\0\1\5\2\0\1\5\4\0\2\5"+
    "\1\142\17\5\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3168];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\1\11\12\1\4\11"+
    "\3\1\6\11\1\0\1\1\2\0\2\1\1\0\12\1"+
    "\4\11\3\1\1\11\1\1\2\0\12\1\1\0\2\1"+
    "\1\0\1\1\1\0\12\1\1\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private StringBuffer stringBuffer = new StringBuffer();
    private ComplexSymbolFactory symbolFactory;

    public TinyJavaLexer(Reader input, ComplexSymbolFactory symbolFactory) {
        this(input);
        this.symbolFactory = symbolFactory;
    }

    private Symbol symbol(String name, int token) {
        return symbol(name, token, null);
    }

    private Symbol symbol(String name, int token, Object value) {
        int line = yyline + 1;
        Location left = new Location(line, yycolumn + 1, yychar);
        Location right = new Location(line, yycolumn + yylength(), yychar + yylength());
        return symbolFactory.newSymbol(name, token, left, right, value);
    }

    private void error(String error) {
        System.out.println("Error on line " + (yyline + 1) + ", at col " + (yycolumn + 1) + " : " + error);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TinyJavaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2930) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbolFactory.newSymbol("EOF", EOF, new Location(yyline + 1, yycolumn + 1, yychar), new Location(yyline + 1, yycolumn + 1, yychar + 1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error("Unrecognized character " + yytext());
            } 
            // fall through
          case 38: break;
          case 2: 
            { /* IGNORE WhiteSpace */
            } 
            // fall through
          case 39: break;
          case 3: 
            { return symbol("Identifier", IDENTIFIER, yytext());
            } 
            // fall through
          case 40: break;
          case 4: 
            { return symbol("DecimalInteger", DECIMAL_INTEGER, Integer.parseInt(yytext()));
            } 
            // fall through
          case 41: break;
          case 5: 
            { return symbol("-", MINUS);
            } 
            // fall through
          case 42: break;
          case 6: 
            { return symbol("/", DIVIDE);
            } 
            // fall through
          case 43: break;
          case 7: 
            { return symbol("*", TIMES);
            } 
            // fall through
          case 44: break;
          case 8: 
            { return symbol("=", EQUALS);
            } 
            // fall through
          case 45: break;
          case 9: 
            { return symbol("+", PLUS);
            } 
            // fall through
          case 46: break;
          case 10: 
            { return symbol(";", SEMICOLON);
            } 
            // fall through
          case 47: break;
          case 11: 
            { return symbol(",", COMMA);
            } 
            // fall through
          case 48: break;
          case 12: 
            { return symbol(".", PERIOD);
            } 
            // fall through
          case 49: break;
          case 13: 
            { return symbol("<", LESS_THAN);
            } 
            // fall through
          case 50: break;
          case 14: 
            { return symbol(">", GREATER_THAN);
            } 
            // fall through
          case 51: break;
          case 15: 
            { return symbol("]", RIGHT_BRACKET);
            } 
            // fall through
          case 52: break;
          case 16: 
            { return symbol("[", LEFT_BRACKET);
            } 
            // fall through
          case 53: break;
          case 17: 
            { return symbol(")", RIGHT_PAREN);
            } 
            // fall through
          case 54: break;
          case 18: 
            { return symbol("(", LEFT_PAREN);
            } 
            // fall through
          case 55: break;
          case 19: 
            { return symbol("{", LEFT_CURLY_BRACE);
            } 
            // fall through
          case 56: break;
          case 20: 
            { return symbol("}", RIGHT_CURLY_BRACE);
            } 
            // fall through
          case 57: break;
          case 21: 
            { return symbol("StringLiteral", STRING_LITERAL, yytext());
            } 
            // fall through
          case 58: break;
          case 22: 
            { /* IGNORE Comment */
            } 
            // fall through
          case 59: break;
          case 23: 
            { return symbol("if", IF);
            } 
            // fall through
          case 60: break;
          case 24: 
            { return symbol("==", DOUBLE_EQUALS);
            } 
            // fall through
          case 61: break;
          case 25: 
            { return symbol("!=", NOT_EQUALS);
            } 
            // fall through
          case 62: break;
          case 26: 
            { return symbol("<=", LESS_THAN_EQUALS);
            } 
            // fall through
          case 63: break;
          case 27: 
            { return symbol(">=", GREATER_THAN_EQUALS);
            } 
            // fall through
          case 64: break;
          case 28: 
            { return symbol("FloatingPoint", FLOATING_POINT, Float.parseFloat(yytext()));
            } 
            // fall through
          case 65: break;
          case 29: 
            { return symbol("int", INT);
            } 
            // fall through
          case 66: break;
          case 30: 
            { return symbol("else", ELSE);
            } 
            // fall through
          case 67: break;
          case 31: 
            { return symbol("void", VOID);
            } 
            // fall through
          case 68: break;
          case 32: 
            { return symbol("while", WHILE);
            } 
            // fall through
          case 69: break;
          case 33: 
            { return symbol("class", CLASS);
            } 
            // fall through
          case 70: break;
          case 34: 
            { return symbol("static", STATIC);
            } 
            // fall through
          case 71: break;
          case 35: 
            { return symbol("return", RETURN);
            } 
            // fall through
          case 72: break;
          case 36: 
            { return symbol("public", PUBLIC);
            } 
            // fall through
          case 73: break;
          case 37: 
            { return symbol("double", DOUBLE);
            } 
            // fall through
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
