/* The following code was generated by JFlex 1.7.0 */

package grammar;

import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;

import static grammar.Token.*;

import java.io.Reader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/Users/smg247/Projects/COFC/CSIS618/tinyJavaCompiler/src/main/java/grammar/grammar.jflex</tt>
 */
public class TinyJavaLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\11\1\11\1\11\1\11\22\0\1\16\1\41\6\0"+
    "\1\47\1\46\1\15\1\37\1\0\1\10\1\14\1\17\1\4\11\3"+
    "\1\0\1\40\1\42\1\36\1\43\2\0\4\1\1\7\1\13\24\1"+
    "\1\45\1\0\1\44\1\0\1\1\1\0\1\30\1\22\1\25\1\33"+
    "\1\34\1\12\2\1\1\24\2\1\1\23\1\1\1\35\1\32\1\20"+
    "\2\1\1\26\1\27\1\21\1\31\4\1\1\50\1\6\1\51\7\0"+
    "\1\11\32\0\1\16\11\0\1\2\12\0\1\2\4\0\1\2\5\0"+
    "\27\2\1\0\37\2\1\0\u01ca\2\4\0\14\2\16\0\5\2\7\0"+
    "\1\2\1\0\1\2\21\0\165\2\1\0\2\2\2\0\4\2\1\0"+
    "\1\2\6\0\1\2\1\0\3\2\1\0\1\2\1\0\24\2\1\0"+
    "\123\2\1\0\213\2\1\0\255\2\1\0\46\2\2\0\1\2\7\0"+
    "\47\2\11\0\55\2\1\0\1\2\1\0\2\2\1\0\2\2\1\0"+
    "\1\2\10\0\33\2\5\0\3\2\35\0\13\2\5\0\100\2\12\5"+
    "\4\0\146\2\1\0\10\2\2\0\12\2\1\0\6\2\12\5\3\2"+
    "\2\0\1\2\20\0\73\2\2\0\145\2\16\0\12\5\54\2\4\0"+
    "\1\2\5\0\56\2\22\0\34\2\104\0\25\2\1\0\10\2\26\0"+
    "\16\2\1\0\201\2\2\0\12\5\1\0\23\2\1\0\10\2\2\0"+
    "\2\2\2\0\26\2\1\0\7\2\1\0\1\2\3\0\4\2\2\0"+
    "\11\2\2\0\2\2\2\0\4\2\10\0\1\2\4\0\2\2\1\0"+
    "\5\2\2\0\12\5\2\2\17\0\3\2\1\0\6\2\4\0\2\2"+
    "\2\0\26\2\1\0\7\2\1\0\2\2\1\0\2\2\1\0\2\2"+
    "\2\0\1\2\1\0\5\2\4\0\2\2\2\0\3\2\3\0\1\2"+
    "\7\0\4\2\1\0\1\2\7\0\12\5\6\2\13\0\3\2\1\0"+
    "\11\2\1\0\3\2\1\0\26\2\1\0\7\2\1\0\2\2\1\0"+
    "\5\2\2\0\12\2\1\0\3\2\1\0\3\2\2\0\1\2\17\0"+
    "\4\2\2\0\12\5\11\0\1\2\7\0\3\2\1\0\10\2\2\0"+
    "\2\2\2\0\26\2\1\0\7\2\1\0\2\2\1\0\5\2\2\0"+
    "\11\2\2\0\2\2\2\0\3\2\10\0\2\2\4\0\2\2\1\0"+
    "\5\2\2\0\12\5\1\0\1\2\20\0\2\2\1\0\6\2\3\0"+
    "\3\2\1\0\4\2\3\0\2\2\1\0\1\2\1\0\2\2\3\0"+
    "\2\2\3\0\3\2\3\0\14\2\4\0\5\2\3\0\3\2\1\0"+
    "\4\2\2\0\1\2\6\0\1\2\16\0\12\5\20\0\4\2\1\0"+
    "\10\2\1\0\3\2\1\0\27\2\1\0\20\2\3\0\10\2\1\0"+
    "\3\2\1\0\4\2\7\0\2\2\1\0\3\2\5\0\4\2\2\0"+
    "\12\5\20\0\4\2\1\0\10\2\1\0\3\2\1\0\27\2\1\0"+
    "\12\2\1\0\5\2\2\0\11\2\1\0\3\2\1\0\4\2\7\0"+
    "\2\2\7\0\1\2\1\0\4\2\2\0\12\5\1\0\2\2\16\0"+
    "\3\2\1\0\10\2\1\0\3\2\1\0\51\2\2\0\10\2\1\0"+
    "\3\2\1\0\5\2\5\0\4\2\7\0\5\2\2\0\12\5\12\0"+
    "\6\2\2\0\2\2\1\0\22\2\3\0\30\2\1\0\11\2\1\0"+
    "\1\2\2\0\7\2\3\0\1\2\4\0\6\2\1\0\1\2\1\0"+
    "\10\2\6\0\12\5\2\0\2\2\15\0\72\2\5\0\17\2\1\0"+
    "\12\5\47\0\2\2\1\0\1\2\2\0\2\2\1\0\1\2\2\0"+
    "\1\2\6\0\4\2\1\0\7\2\1\0\3\2\1\0\1\2\1\0"+
    "\1\2\2\0\2\2\1\0\15\2\1\0\3\2\2\0\5\2\1\0"+
    "\1\2\1\0\6\2\2\0\12\5\2\0\4\2\40\0\1\2\27\0"+
    "\2\2\6\0\12\5\13\0\1\2\1\0\1\2\1\0\1\2\4\0"+
    "\12\2\1\0\44\2\4\0\24\2\1\0\22\2\1\0\44\2\11\0"+
    "\1\2\71\0\100\2\12\5\6\0\100\2\12\5\4\2\2\0\46\2"+
    "\1\0\1\2\5\0\1\2\2\0\53\2\1\0\u014d\2\1\0\4\2"+
    "\2\0\7\2\1\0\1\2\1\0\4\2\2\0\51\2\1\0\4\2"+
    "\2\0\41\2\1\0\4\2\2\0\7\2\1\0\1\2\1\0\4\2"+
    "\2\0\17\2\1\0\71\2\1\0\4\2\2\0\103\2\2\0\3\2"+
    "\40\0\20\2\20\0\126\2\2\0\6\2\3\0\u026c\2\2\0\21\2"+
    "\1\16\32\2\5\0\113\2\3\0\13\2\7\0\15\2\1\0\7\2"+
    "\13\0\25\2\13\0\24\2\14\0\15\2\1\0\3\2\1\0\2\2"+
    "\14\0\124\2\3\0\1\2\4\0\2\2\2\0\12\5\41\0\3\2"+
    "\2\0\12\5\6\0\130\2\10\0\53\2\5\0\106\2\12\0\37\2"+
    "\1\0\14\2\4\0\14\2\12\0\12\5\36\2\2\0\5\2\13\0"+
    "\54\2\4\0\32\2\6\0\12\5\46\0\34\2\4\0\77\2\1\0"+
    "\35\2\2\0\1\2\12\5\6\0\12\5\15\0\1\2\10\0\17\2"+
    "\101\0\114\2\4\0\12\5\21\0\11\2\14\0\60\2\12\5\72\2"+
    "\14\0\70\2\10\0\12\5\3\0\3\2\12\5\44\2\2\0\11\2"+
    "\107\0\3\2\1\0\43\2\1\0\2\2\6\0\366\2\5\0\u011b\2"+
    "\2\0\6\2\2\0\46\2\2\0\6\2\2\0\10\2\1\0\1\2"+
    "\1\0\1\2\1\0\1\2\1\0\37\2\2\0\65\2\1\0\7\2"+
    "\1\0\1\2\3\0\3\2\1\0\7\2\3\0\4\2\2\0\6\2"+
    "\4\0\15\2\5\0\3\2\1\0\7\2\3\0\13\16\35\0\1\11"+
    "\1\11\5\0\1\16\17\0\2\2\23\0\1\2\12\0\1\16\21\0"+
    "\1\2\15\0\1\2\20\0\15\2\63\0\41\2\21\0\1\2\4\0"+
    "\1\2\2\0\12\2\1\0\1\2\3\0\5\2\6\0\1\2\1\0"+
    "\1\2\1\0\1\2\1\0\4\2\1\0\13\2\2\0\4\2\5\0"+
    "\5\2\4\0\1\2\21\0\51\2\u032d\0\64\2\u0716\0\57\2\1\0"+
    "\57\2\1\0\205\2\6\0\11\2\14\0\46\2\1\0\1\2\5\0"+
    "\1\2\2\0\70\2\7\0\1\2\17\0\30\2\11\0\7\2\1\0"+
    "\7\2\1\0\7\2\1\0\7\2\1\0\7\2\1\0\7\2\1\0"+
    "\7\2\1\0\7\2\1\0\40\2\57\0\1\2\u01d0\0\1\16\4\0"+
    "\3\2\31\0\17\2\1\0\5\2\2\0\5\2\4\0\126\2\2\0"+
    "\2\2\2\0\3\2\1\0\132\2\1\0\4\2\5\0\51\2\3\0"+
    "\136\2\21\0\33\2\65\0\20\2\u0200\0\u19b6\2\112\0\u51d6\2\52\0"+
    "\u048d\2\103\0\56\2\2\0\u010d\2\3\0\20\2\12\5\2\2\24\0"+
    "\63\2\1\0\12\2\1\0\163\2\45\0\11\2\2\0\147\2\2\0"+
    "\44\2\1\0\10\2\77\0\61\2\30\0\64\2\14\0\106\2\12\0"+
    "\12\5\6\0\30\2\3\0\1\2\1\0\1\2\2\0\12\5\44\2"+
    "\2\0\44\2\14\0\35\2\3\0\101\2\16\0\1\2\12\5\6\0"+
    "\20\2\12\5\5\2\1\0\67\2\11\0\16\2\2\0\12\5\6\0"+
    "\27\2\3\0\111\2\30\0\3\2\2\0\20\2\2\0\5\2\12\0"+
    "\6\2\2\0\6\2\2\0\6\2\11\0\7\2\1\0\7\2\1\0"+
    "\53\2\1\0\12\2\12\0\173\2\1\0\2\2\2\0\12\5\6\0"+
    "\u2ba4\2\14\0\27\2\4\0\61\2\u2104\0\u016e\2\2\0\152\2\46\0"+
    "\7\2\14\0\5\2\5\0\14\2\1\0\15\2\1\0\5\2\1\0"+
    "\1\2\1\0\2\2\1\0\2\2\1\0\154\2\41\0\u016b\2\22\0"+
    "\100\2\2\0\66\2\50\0\14\2\4\0\20\2\20\0\20\2\3\0"+
    "\2\2\30\0\3\2\40\0\5\2\1\0\207\2\23\0\12\5\7\0"+
    "\32\2\4\0\1\2\1\0\32\2\13\0\131\2\3\0\6\2\2\0"+
    "\6\2\2\0\6\2\2\0\3\2\43\0\14\2\1\0\32\2\1\0"+
    "\23\2\1\0\2\2\1\0\17\2\2\0\16\2\42\0\173\2\105\0"+
    "\65\2\210\0\1\2\202\0\35\2\3\0\61\2\17\0\1\2\37\0"+
    "\40\2\20\0\33\2\5\0\53\2\5\0\36\2\2\0\44\2\4\0"+
    "\10\2\1\0\5\2\52\0\236\2\2\0\12\5\6\0\44\2\4\0"+
    "\44\2\4\0\50\2\10\0\64\2\234\0\u0137\2\11\0\26\2\12\0"+
    "\10\2\230\0\6\2\2\0\1\2\1\0\54\2\1\0\2\2\3\0"+
    "\1\2\2\0\27\2\12\0\27\2\11\0\37\2\101\0\23\2\1\0"+
    "\2\2\12\0\26\2\12\0\32\2\106\0\70\2\6\0\2\2\100\0"+
    "\4\2\1\0\2\2\5\0\10\2\1\0\3\2\1\0\33\2\4\0"+
    "\3\2\4\0\1\2\40\0\35\2\3\0\35\2\43\0\10\2\1\0"+
    "\36\2\31\0\66\2\12\0\26\2\12\0\23\2\15\0\22\2\156\0"+
    "\111\2\67\0\63\2\15\0\63\2\u030d\0\107\2\37\0\12\5\17\0"+
    "\74\2\25\0\31\2\7\0\12\5\6\0\65\2\1\0\12\5\20\0"+
    "\44\2\2\0\1\2\11\0\105\2\5\0\3\2\3\0\12\5\1\2"+
    "\1\0\1\2\43\0\22\2\1\0\45\2\6\0\1\2\101\0\7\2"+
    "\1\0\1\2\1\0\4\2\1\0\17\2\1\0\12\2\7\0\73\2"+
    "\5\0\12\5\6\0\4\2\1\0\10\2\2\0\2\2\2\0\26\2"+
    "\1\0\7\2\1\0\2\2\1\0\5\2\2\0\11\2\2\0\2\2"+
    "\2\0\3\2\2\0\1\2\6\0\1\2\5\0\7\2\2\0\7\2"+
    "\3\0\5\2\213\0\113\2\5\0\12\5\46\0\106\2\1\0\1\2"+
    "\10\0\12\5\246\0\66\2\2\0\11\2\27\0\6\2\42\0\101\2"+
    "\3\0\1\2\13\0\12\5\46\0\70\2\10\0\12\5\66\0\32\2"+
    "\3\0\17\2\4\0\12\5\u0166\0\100\2\12\5\25\0\1\2\u01c0\0"+
    "\71\2\u0107\0\11\2\1\0\55\2\1\0\11\2\17\0\12\5\30\0"+
    "\36\2\2\0\26\2\1\0\16\2\u0349\0\u039a\2\146\0\157\2\21\0"+
    "\304\2\u0abc\0\u042f\2\u0fd1\0\u0247\2\u21b9\0\u0239\2\7\0\37\2\1\0"+
    "\12\5\146\0\36\2\2\0\5\2\13\0\67\2\11\0\4\2\14\0"+
    "\12\5\11\0\25\2\5\0\23\2\u0370\0\105\2\13\0\57\2\20\0"+
    "\21\2\100\0\1\2\37\0\u17ed\2\23\0\u02f3\2\u250d\0\2\2\u0bfe\0"+
    "\153\2\5\0\15\2\3\0\11\2\7\0\12\2\3\0\2\2\u14c6\0"+
    "\5\2\3\0\6\2\10\0\10\2\2\0\7\2\36\0\4\2\224\0"+
    "\3\2\u01bb\0\125\2\1\0\107\2\1\0\2\2\2\0\1\2\2\0"+
    "\2\2\2\0\4\2\1\0\14\2\1\0\1\2\1\0\7\2\1\0"+
    "\101\2\1\0\4\2\2\0\10\2\1\0\7\2\1\0\34\2\1\0"+
    "\4\2\1\0\5\2\1\0\1\2\3\0\7\2\1\0\u0154\2\2\0"+
    "\31\2\1\0\31\2\1\0\37\2\1\0\31\2\1\0\37\2\1\0"+
    "\31\2\1\0\37\2\1\0\31\2\1\0\37\2\1\0\31\2\1\0"+
    "\10\2\2\0\62\5\u0200\0\67\2\4\0\62\2\10\0\1\2\16\0"+
    "\1\2\26\0\5\2\1\0\17\2\u0550\0\7\2\1\0\21\2\2\0"+
    "\7\2\1\0\2\2\1\0\5\2\u07d5\0\305\2\13\0\7\2\51\0"+
    "\113\2\5\0\12\5\u04a6\0\4\2\1\0\33\2\1\0\2\2\1\0"+
    "\1\2\2\0\1\2\1\0\12\2\1\0\4\2\1\0\1\2\1\0"+
    "\1\2\6\0\1\2\4\0\1\2\1\0\1\2\1\0\1\2\1\0"+
    "\3\2\1\0\2\2\1\0\1\2\2\0\1\2\1\0\1\2\1\0"+
    "\1\2\1\0\1\2\1\0\1\2\1\0\2\2\1\0\1\2\2\0"+
    "\4\2\1\0\7\2\1\0\4\2\1\0\4\2\1\0\1\2\1\0"+
    "\12\2\1\0\21\2\5\0\3\2\1\0\5\2\1\0\21\2\u0274\0"+
    "\32\2\6\0\32\2\6\0\32\2\u0e76\0\ua6d7\2\51\0\u1035\2\13\0"+
    "\336\2\2\0\u1682\2\u295e\0\u021e\2\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\2\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\3\1\1\2\1\3\1\4\1\5\2\6\6\1"+
    "\1\7\1\10\1\11\1\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\0\1\2\2\0"+
    "\1\22\1\0\1\22\1\23\6\22\1\24\1\25\1\26"+
    "\1\27\1\5\1\2\4\5\1\0\1\30\4\0\1\5"+
    "\1\0\1\5\3\0\1\31\2\0\1\32\2\0\1\33"+
    "\1\34\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\124\0\124"+
    "\0\374\0\u0126\0\124\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8"+
    "\0\u0222\0\u024c\0\124\0\124\0\u0276\0\u02a0\0\u02ca\0\124"+
    "\0\124\0\124\0\124\0\124\0\124\0\124\0\u02f4\0\u031e"+
    "\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03c6\0\124\0\u03f0\0\u041a"+
    "\0\u0444\0\u046e\0\u0498\0\u04c2\0\124\0\124\0\124\0\124"+
    "\0\u04ec\0\u0516\0\u0540\0\u056a\0\u039c\0\124\0\u0594\0\124"+
    "\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0738\0\124\0\u0762\0\u078c\0\124\0\u07b6\0\u07e0"+
    "\0\124\0\124\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\5\1\3\1\4"+
    "\1\7\1\10\1\4\1\11\1\12\1\13\1\10\1\13"+
    "\1\14\3\4\1\15\1\16\1\17\2\4\1\20\1\4"+
    "\1\21\2\4\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\52\3\53\0"+
    "\5\36\1\0\1\36\2\0\2\36\4\0\16\36\17\0"+
    "\1\6\46\0\3\37\1\40\1\41\1\42\3\37\1\0"+
    "\40\37\1\0\2\36\3\43\1\44\1\45\2\0\2\36"+
    "\4\0\14\36\1\45\1\36\31\0\1\46\35\0\5\36"+
    "\1\0\1\36\2\0\2\36\4\0\1\36\1\47\14\36"+
    "\15\0\5\36\1\0\1\36\2\0\2\36\4\0\15\36"+
    "\1\50\15\0\5\36\1\0\1\36\2\0\2\36\4\0"+
    "\3\36\1\51\12\36\15\0\5\36\1\0\1\36\2\0"+
    "\2\36\4\0\7\36\1\52\6\36\15\0\5\36\1\0"+
    "\1\36\2\0\2\36\4\0\12\36\1\53\3\36\15\0"+
    "\5\36\1\0\1\36\2\0\2\36\4\0\12\36\1\54"+
    "\3\36\52\0\1\55\51\0\1\56\51\0\1\57\51\0"+
    "\1\60\16\0\3\61\44\0\3\37\1\62\1\63\1\64"+
    "\3\37\1\0\43\37\2\63\1\64\3\37\1\0\40\37"+
    "\3\0\1\63\2\61\47\0\3\65\47\0\4\66\1\0"+
    "\1\66\26\0\1\66\34\0\1\67\56\0\1\70\52\0"+
    "\1\71\51\0\1\72\45\0\1\73\46\0\1\74\33\0"+
    "\3\61\2\44\2\0\1\75\21\0\1\44\15\0\3\37"+
    "\1\62\1\63\1\64\2\76\1\37\1\0\1\77\21\37"+
    "\1\76\20\37\2\63\1\64\2\76\1\37\1\0\1\77"+
    "\21\37\1\76\15\37\3\0\1\63\2\61\2\44\2\0"+
    "\1\75\21\0\1\44\40\0\1\100\54\0\1\101\52\0"+
    "\1\102\55\0\1\103\40\0\1\104\32\0\3\65\2\44"+
    "\24\0\1\44\20\0\3\61\1\66\1\0\1\66\26\0"+
    "\1\66\15\0\3\61\2\44\24\0\1\44\41\0\1\105"+
    "\53\0\1\106\47\0\1\107\50\0\1\110\53\0\1\111"+
    "\51\0\1\112\60\0\1\113\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2058];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\2\11\2\1\1\11\7\1\2\11"+
    "\3\1\7\11\1\0\1\1\2\0\1\1\1\0\1\1"+
    "\1\11\6\1\4\11\5\1\1\11\1\0\1\11\4\0"+
    "\1\1\1\0\1\1\3\0\1\11\2\0\1\11\2\0"+
    "\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private StringBuffer stringBuffer = new StringBuffer();
    private ComplexSymbolFactory symbolFactory;

    public TinyJavaLexer(Reader input, ComplexSymbolFactory symbolFactory) {
        this(input);
        this.symbolFactory = symbolFactory;
    }

    private Symbol symbol(String name, Token token) {
        return symbol(name, token, null);
    }

    private Symbol symbol(String name, Token token, Object value) {
        int line = yyline + 1;
        Location left = new Location(line, yycolumn + 1, yychar);
        Location right = new Location(line, yycolumn + yylength(), yychar + yylength());
        return symbolFactory.newSymbol(name, token.ordinal(), left, right, value);
    }

    private void error(String error) {
        System.out.println("Error on line " + (yyline + 1) + ", at col " + (yycolumn + 1) + " : " + error);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TinyJavaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2922) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbolFactory.newSymbol("EOF", EOF.ordinal(), new Location(yyline + 1, yycolumn + 1, yychar), new Location(yyline + 1, yycolumn + 1, yychar + 1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error("Unrecognized character " + yytext());
            } 
            // fall through
          case 30: break;
          case 2: 
            { return symbol("DecimalInteger", DECIMAL_INTEGER, Integer.parseInt(yytext()));
            } 
            // fall through
          case 31: break;
          case 3: 
            { return symbol("-", MINUS);
            } 
            // fall through
          case 32: break;
          case 4: 
            { /* IGNORE WhiteSpace */
            } 
            // fall through
          case 33: break;
          case 5: 
            { return symbol("FloatingPoint", FLOATING_POINT, Float.parseFloat(yytext()));
            } 
            // fall through
          case 34: break;
          case 6: 
            { /* IGNORE Comment */
            } 
            // fall through
          case 35: break;
          case 7: 
            { return symbol("=", EQUALS);
            } 
            // fall through
          case 36: break;
          case 8: 
            { return symbol("+", PLUS);
            } 
            // fall through
          case 37: break;
          case 9: 
            { return symbol(";", SEMICOLON);
            } 
            // fall through
          case 38: break;
          case 10: 
            { return symbol("<", LESS_THAN);
            } 
            // fall through
          case 39: break;
          case 11: 
            { return symbol(">", GREATER_THAN);
            } 
            // fall through
          case 40: break;
          case 12: 
            { return symbol("]", RIGHT_BRACKET);
            } 
            // fall through
          case 41: break;
          case 13: 
            { return symbol("[", LEFT_BRACKET);
            } 
            // fall through
          case 42: break;
          case 14: 
            { return symbol(")", RIGHT_PAREN);
            } 
            // fall through
          case 43: break;
          case 15: 
            { return symbol("(", LEFT_PAREN);
            } 
            // fall through
          case 44: break;
          case 16: 
            { return symbol("{", LEFT_CURLY_BRACE);
            } 
            // fall through
          case 45: break;
          case 17: 
            { return symbol("}", RIGHT_CURLY_BRACE);
            } 
            // fall through
          case 46: break;
          case 18: 
            { return symbol("Identifier", IDENTIFIER, yytext());
            } 
            // fall through
          case 47: break;
          case 19: 
            { return symbol("StringLiteral", STRING_LITERAL, yytext());
            } 
            // fall through
          case 48: break;
          case 20: 
            { return symbol("==", DOUBLE_EQUALS);
            } 
            // fall through
          case 49: break;
          case 21: 
            { return symbol("!=", NOT_EQUALS);
            } 
            // fall through
          case 50: break;
          case 22: 
            { return symbol("<=", LESS_THAN_EQUALS);
            } 
            // fall through
          case 51: break;
          case 23: 
            { return symbol(">=", GREATER_THAN_EQUALS);
            } 
            // fall through
          case 52: break;
          case 24: 
            { return symbol("int", INT);
            } 
            // fall through
          case 53: break;
          case 25: 
            { return symbol("void", VOID);
            } 
            // fall through
          case 54: break;
          case 26: 
            { return symbol("class", CLASS);
            } 
            // fall through
          case 55: break;
          case 27: 
            { return symbol("public", PUBLIC);
            } 
            // fall through
          case 56: break;
          case 28: 
            { return symbol("static", STATIC);
            } 
            // fall through
          case 57: break;
          case 29: 
            { return symbol("double", DOUBLE);
            } 
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
