
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package grammar;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int RIGHT_CURLY_BRACE = 17;
  public static final int CLASS = 7;
  public static final int SEMICOLON = 14;
  public static final int PLUS = 26;
  public static final int INT = 18;
  public static final int LEFT_PAREN = 11;
  public static final int DOUBLE_EQUALS = 20;
  public static final int GREATER_THAN = 23;
  public static final int IDENTIFIER = 2;
  public static final int PUBLIC = 6;
  public static final int GREATER_THAN_EQUALS = 25;
  public static final int STATIC = 8;
  public static final int STRING_LITERAL = 5;
  public static final int EQUALS = 13;
  public static final int EOF = 0;
  public static final int LESS_THAN = 22;
  public static final int MINUS = 27;
  public static final int DECIMAL_INTEGER = 3;
  public static final int NOT_EQUALS = 21;
  public static final int LEFT_BRACKET = 9;
  public static final int error = 1;
  public static final int LESS_THAN_EQUALS = 24;
  public static final int RIGHT_PAREN = 12;
  public static final int FLOATING_POINT = 4;
  public static final int VOID = 15;
  public static final int DOUBLE = 19;
  public static final int RIGHT_BRACKET = 10;
  public static final int LEFT_CURLY_BRACE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "DECIMAL_INTEGER",
  "FLOATING_POINT",
  "STRING_LITERAL",
  "PUBLIC",
  "CLASS",
  "STATIC",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "EQUALS",
  "SEMICOLON",
  "VOID",
  "LEFT_CURLY_BRACE",
  "RIGHT_CURLY_BRACE",
  "INT",
  "DOUBLE",
  "DOUBLE_EQUALS",
  "NOT_EQUALS",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_THAN_EQUALS",
  "GREATER_THAN_EQUALS",
  "PLUS",
  "MINUS"
  };
}

